export interface ShopwareProduct {
  data: ShopwareProductData[]
}

export interface ShopwareProductData {
  id: number
  mainDetailId: number
  supplierId: number
  taxId: number
  priceGroupId: number
  filterGroupId?: number
  configuratorSetId?: number
  name: string
  description: string
  descriptionLong: string
  added: string
  active: boolean
  pseudoSales: number
  highlight: boolean
  keywords: string
  metaTitle?: string
  changed: string
  priceGroupActive: boolean
  lastStock: boolean
  crossBundleLook: number
  notification: boolean
  template: string
  mode: number
  availableFrom: any
  availableTo: any
  mainDetail: MainDetail
}

export interface MainDetail {
  id: number
  articleId: number
  unitId: number
  number: string
  supplierNumber: string
  kind: number
  additionalText?: string
  active: boolean
  inStock: number
  stockMin: number
  lastStock: boolean
  weight?: string
  width?: string
  len?: string
  height?: string
  ean: string
  purchasePrice: number
  position: number
  minPurchase: number
  purchaseSteps: any
  maxPurchase?: number
  purchaseUnit: any
  referenceUnit: any
  packUnit?: string
  shippingFree: boolean
  releaseDate: string
  shippingTime: string
  attribute: Attribute
}

export interface Attribute {
  id: number
  articleDetailId: number
  attr1?: string
  attr2?: string
  attr3?: string
  attr4?: string
  attr5?: string
  attr6?: string
  attr7?: string
  attr8?: string
  attr9?: string
  attr10?: string
  attr11?: string
  attr12?: string
  attr13?: string
  attr14?: string
  attr15?: string
  attr16?: string
  attr17?: string
  attr18?: string
  attr19?: string
  attr20?: string
  dreiscSeoUrl: string
  dreiscSeoTitle: string
  dreiscSeoTitleReplace: number
  dreiscSeoBreadcrumb?: string
  dreiscCanonicalLink?: string
  dreiscRobotsTag: string
  dreiscFacebookDescription: string
  dreiscTwitterDescription: string
  dreiscFacebookImage?: string
  dreiscTwitterImage?: string
  maxorderprocessingtime: string
  pickwareIncomingStock: number
  pickwarePhysicalStockForSale: number
  pickwareStockManagementDisabled: boolean
  pickwareStockInitialized: boolean
  pickwareStockInitializationTime: string
  pickwareNotRelevantForPicking: boolean
  pickwareWmsInternalPickingInstructions?: string
  viisonCountryOfOrigin?: number
  viisonCustomsTariffNumber?: string
  swkweShowSoldout: number
  swkweCategoryShowSoldout: number
  viisonMoss?: boolean
  viisonOtherServiceParagraphOneOrTwo?: boolean
  viisonDatevCostCenter?: string
  idealoDirektkauf: number
  wish: string
  auslauf: number
  nomarketplace: number
  scha1Tabfield1?: string
  scha1Tabfield2?: string
  scha1Tabfield3?: string
  scha1Tabfield4?: string
  scha1Tabfield5?: string
  scha1Tabfield6?: string
  scha1Tabfield7?: string
  scha1Tabfield8?: string
  scha1Tabfield9?: string
  scha1Tabfield10?: string
  pixupExcludeSitemap: number
  pixupLinkPriority: any
  pixupLinkLinkChangeFrequenzy: any
  verbandsnummer?: string
  idennummer?: string
  digi1Showleftsidebar: number
  attrBulkyGoods: number
  warengruppe?: string
  scha1Tabfield1Io: number
  scha1Tabfield2Io: number
  scha1Tabfield3Io: number
  scha1Tabfield4Io: number
  scha1Tabfield5Io: number
  scha1Tabfield6Io: number
  scha1Tabfield7Io: number
  scha1Tabfield8Io: number
  scha1Tabfield9Io: number
  scha1Tabfield10Io: number
  warengruppeName?: string
  repricing: number
  compraArticleLogosPosition: any
  compraArticleLogo1Url?: string
  compraArticleLogo1Tooltip?: string
  compraArticleLogo2Url?: string
  compraArticleLogo2Tooltip?: string
  compraArticleLogo3Url?: string
  compraArticleLogo3Tooltip?: string
  compraArticleLogo4Url?: string
  compraArticleLogo4Tooltip?: string
  ottoGroup?: string
  preisbindung: number
  ottoGroupAktiv: number
  sortierterArtikel?: number
  sonderposten: number
  googleVerfuegbarkeit: string
  aktionspreisBefristet: number
  untersterpreis?: string
  hoechstpreis?: string
  dvsnArticleShippingMethodRestriction: string
  bullet_1?: string
  bullet_2?: string
  bullet_3?: string
  bullet_4?: string
  bullet_5?: string
  ebayBezeichnung?: string
  mollieVoucherType: any
  bearbeitungsstandPh?: string
  eigenschaftenBearbeitet?: number
  preisparitaetCheck24?: number
  legoendoflive: any
}